DROP TABLE IF EXISTS PERSONS;

CREATE TABLE PERSONS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    address VARCHAR(250) NOT NULL,
    city VARCHAR(50) NOT NULL,
    zip INT NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(250) NOT NULL
);